### ISSUE TITLE
Problems with viz.py

### ISSUE THREAD

**Issue by truell20** [openai/evolution-strategies-starter#1]
I'm having a bit of trouble with `viz.py`

When I run it like so:

    sudo python3 -m scripts.viz Humanoid-v1 /tmp/es_master_25626/snapshot_iter00000_rew279.h5 --record --stochastic

I get errors like this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1021, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1003, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value MujocoPolicy/ob_mean
	 [[Node: MujocoPolicy/ob_mean/read = Identity[T=DT_FLOAT, _class=["loc:@MujocoPolicy/ob_mean"], _device="/job:localhost/replica:0/task:0/cpu:0"](MujocoPolicy/ob_mean)]]
```

**Comment by truell20** [comment]
Bump

**Comment by truell20** [comment]
?
